# Generated by Django 3.1.7 on 2021-04-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_databases_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='databases',
            name='IP',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
