# Generated by Django 3.1.7 on 2021-04-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_databases_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databases',
            name='IP',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
