# Generated by Django 3.1.7 on 2021-04-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210412_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databases',
            name='IP',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
