# Generated by Django 3.1.7 on 2021-04-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210413_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databases',
            name='IP',
            field=models.GenericIPAddressField(null=True, unpack_ipv4=True),
        ),
    ]
