# Generated by Django 3.1.7 on 2021-04-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210414_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databases',
            name='IP',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
