# Generated by Django 3.1.7 on 2021-04-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210414_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databases',
            name='IP',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
